services:
  - type: web
    name: waingo-farm-pos
    env: docker
    plan: starter
    region: frankfurt
    envVars:
      - key: APP_NAME
        value: "Waingo Farm Agrovet"
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://waingo-farm-pos.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: waingo-pos-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: waingo-pos-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: waingo-pos-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: waingo-pos-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: waingo-pos-db
          property: password
      - key: LOG_CHANNEL
        value: stack
      - key: LOG_LEVEL
        value: error
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database

databases:
  - name: waingo-pos-db
    region: frankfurt
